### ISSUE TITLE
when piping process.stdout, it fails on end()

### ISSUE THREAD

**Issue by eladb** [anodejs/node-farmjs#1]
It seems that it could be easily remedied with:

``` js
if (stream !== process.stdout) {
    stream.end();
}
```

From: Elad Ben-Israel 
Sent: יום ד 11 ינואר 2012 13:01
To: Yosef Dinerstein; Saar Yahalom; Ami Turgman; Fadi Haik
Subject: Re: Uncauht exception from everywhere in anodejs

Let me disable capturing stdout from child processes in reverse proxy. It might be the cause.
I will need your help in recycling the farms because I don't have RDP access…
Elad.

From: Yosef Dinerstein yosefd@MICROSOFT.com
Date: Wed, 11 Jan 2012 12:25:31 +0200
To: ELAD BEN-ISRAEL eladb@microsoft.com, Saar Yahalom saary@microsoft.com, Ami Turgman ami.turgman@microsoft.com, Fadi Haik fadih@microsoft.com
Subject: Uncauht exception from everywhere in anodejs

This happens on many apps in huge volume:

``` js
{
    "level": "error",
    "message": " [\"Uncaught exception:\",\"Error: process.stdout cannot be closed\\n    at Socket.<anonymous> (node.js:284:15)\\n    at Object.afterWrite [as oncomplete] (net.js:478:10)\"]",
    "meta": {
      "time": "2012-01-11T08:06:06.384Z",
      "app": "anode.sys",
      "domain": "anodejs.cloudapp.net",
      "instanceId": "anodejsrole_IN_0",
      "requestID": null,
      "stackTop": "logException (c:\\an\\repo\\master\\node_modules\\anode\\shimme.js:68:48)"
    },
    "_id": "4f0d4331c13c68202401fa63"
  },
```

I guess, this also the trigger to huge logs size and hence the logging performance problem we found.

**Comment by yosefd** [comment]
The exception occurs in applications (child processes). Does it confirm you theory?
